define table position
(
  size [1.5 0.75 0.8]	
   block #TABLE
   (
      points 4
      point[0]  [ 0  0]
      point[1]  [ 1.5 0]
      point[2]  [ 1.5 0.75]
      point[3]  [ 0 0.75]
      z [0.75 0.8]
   )
   block #LEG1
   (
      points 4
      point[0]  [ 0    0]
      point[1]  [ 0.05 0]
      point[2]  [ 0.05 0.05]
      point[3]  [ 0    0.05]
      z [0 0.75]
   )
   block #LEG2
   (
      points 4
      point[0]  [ 1.45 0]
      point[1]  [ 1.5  0]
      point[2]  [ 1.5  0.05]
      point[3]  [ 1.45 0.05]
      z [0 0.75]
   )
   block #LEG3
   (
      points 4
      point[0]  [ 1.45 0.7]
      point[1]  [ 1.5  0.7]
      point[2]  [ 1.5  0.75]
      point[3]  [ 1.45 0.75]
      z [0 0.75]
   )
   block #LEG4
   (
      points 4
      point[0]  [ 0    0.7]
      point[1]  [ 0.05 0.7]
      point[2]  [ 0.05 0.75]
      point[3]  [ 0    0.75]
      z [0 0.75]
   )
   color "brown"	
)
